- name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Bot Debug: Screenshot Included"
          to: ${{ secrets.EMAIL_TO }}
          from: "Museum Bot Debugger"
          body: |
            Check the attached screenshot to see what the bot is seeing!
            
            ---
            ${{ env.TEST_BODY }}
          attachments: debug_screen.png,debug_error.png
